Working branch
JelilFaisalAbudu/private-events1 pull request #12
Opened 2020-09-03 13:56 UTC by JelilFaisalAbudu

# Requesting Code Review for Association(Private Events) Project

* I have finished building the project and it's now ready for your review

## Features of the Project

### Sign-up and Sign-in Processes
* User signs up with his username and email - all required
* Simple log-in process with email address(by using sessions to store user id)

### Interactions with the Webapp
* User can create an event for other to attend
* User can register to attend several events  in case the attendance date hasn't passed

## Unit Testing

* I've performed the unit test for the model(Event, User and Invitation) associations
* Also performed integration test user authentication and event management

### Thank You...

2020-09-03 21:51 UTC, Dandush03 requested changes
# Status: :red_circle: Require Change :red_circle: 
### Great work so far
__IMPORTANT__ before digging in into your code, I most say that your spec is failing when it tries to create a new event when a user is logged in, Apparently you added a field name `location` which is causing the issue.
### Now lest us dive in to your code :wink: 
# Happy Coding :computer: :nerd_face:

2020-09-03 21:51 UTC, Dandush03 commented on config/routes.rb
> +  resources :events, only: [:new, :index, :show, :create, :attended_event, :unattend_event]
__OPTIONAL__: You could use the `except` flag instead of the `only` flag

2020-09-03 21:51 UTC, Dandush03 commented on config/routes.rb
>    delete '/logout', to: 'sessions#destroy'
__OPTIONAL__: You could use resource check out [this link](https://guides.rubyonrails.org/routing.html)

2020-09-04 07:57 UTC, JelilFaisalAbudu commented
# Required Changes have been Made
* There is an unpermitted field which causes the test to fail. It has been resolved and now all specs are passing

2020-09-04 09:03 UTC, rOluochKe approved these changes
Hello @JelilFaisalAbudu 
### You got this right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy hacking!

2020-09-04 11:57 UTC, merged